-- D&D Narrator Bot schema for Supabase/Postgres.
-- The application also creates these tables on first startup for convenience.

create table if not exists public.sessoes (
    chat_id bigint primary key,
    contexto text not null,
    criada_em timestamptz not null,
    atualizada_em timestamptz not null
);

create table if not exists public.personagens (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    chat_id bigint not null,
    nome text not null,
    classe text not null,
    raca text not null,
    atributos text not null,
    historia text not null,
    criado_em timestamptz not null,
    constraint personagens_user_chat_key unique (user_id, chat_id)
);

create table if not exists public.acoes (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    chat_id bigint not null,
    acao text not null,
    resultado text not null,
    feita_em timestamptz not null
);

create index if not exists acoes_chat_id_id_idx
    on public.acoes (chat_id, id desc);
create index if not exists personagens_chat_id_idx
    on public.personagens (chat_id);
